spring:
  application:
    name: storm-zuul

server:
  port: 18081

zuul:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    redis:
      path: /redis/**
      serviceId: storm-cache-redis
    memcache:
      path: /memcache/**
      serviceId: storm-cache-memcache
    user:
      path: /user/**
      serviceId: storm-service-user
      stripPrefix: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18781/eureka/